### PR TITLE
Catch gauge exception to ensure continuous reporting

### LINKED ISSUE #64: DatadogReporter stops reporting to datadog of remaining metric data after throwing Exception during reporting process
Hi guys,

we experienced in the past that some metrics were not reported, after some specific metrics (in our case a gauge, which counts some data) threw an error.

The specific class which is responsible: https://github.com/coursera/metrics-datadog/blob/master/metrics-datadog/src/main/java/org/coursera/metrics/datadog/DatadogReporter.java#L71
If one of the given metrics throws any exception, the other metrics reporter are stopped.

### PR DESCRIPTION
**Pull request by waldemar-schneider**
fixes #64

### CODE REVIEW

File: metrics-datadog/src/main/java/org/coursera/metrics/datadog/DatadogReporter.java [hunk 1]
```diff
@@ -201,12 +201,19 @@ private void reportCounter(String name, Counter counter, long timestamp, List<St
         timestamp, host, tags));
   }
 
-  private void reportGauge(String name, Gauge gauge, long timestamp, List<String> tags)
-      throws IOException {
-    final Number value = toNumber(gauge.getValue());
-    if (value != null) {
-      request.addGauge(new DatadogGauge(metricNameFormatter.format(name), value, timestamp, host,
-          tags));
+  // Gauges are the only metrics which can throw exceptions. With a thrown exception all
```
Comment (nickdella) [inline metrics-datadog/src/main/java/org/coursera/metrics/datadog/DatadogReporter.java]: Should be a Javadoc-style comment per https://google.github.io/styleguide/javaguide.html#s7.3.4-javadoc-non-required .

File: metrics-datadog/src/main/java/org/coursera/metrics/datadog/DatadogReporter.java [hunk 2]
```diff
@@ -201,12 +201,19 @@ private void reportCounter(String name, Counter counter, long timestamp, List<St
...
+  // other metrics will not be reported to Datadog.
+  private void reportGauge(String name, Gauge gauge, long timestamp, List<String> tags) {
+    try {
+      final Number value = toNumber(gauge.getValue());
+      if (value != null) {
+        request.addGauge(new DatadogGauge(metricNameFormatter.format(name), value, timestamp, host,
+                tags));
+      }
+    } catch (Exception exception) {
```
Comment (nickdella) [inline metrics-datadog/src/main/java/org/coursera/metrics/datadog/DatadogReporter.java]: Could just be `e`

File: metrics-datadog/src/main/java/org/coursera/metrics/datadog/DatadogReporter.java [hunk 3]
```diff
@@ -201,12 +201,19 @@ private void reportCounter(String name, Counter counter, long timestamp, List<St
...
+      String errorMessage = String.format("Error reporting gauge metrics (name: %s, tags: %s) to Datadog, " +
```
Comment (nickdella) [inline metrics-datadog/src/main/java/org/coursera/metrics/datadog/DatadogReporter.java]: s/metrics/metric

File: metrics-datadog/src/test/java/org/coursera/metrics/datadog/DatadogReporterTest.java [hunk 4]
```diff
@@ -153,6 +153,29 @@ public void reportsDoubleGaugeValues() throws Exception {
   }
 
   @Test
+  public void reportsGaugeValues_ThrowsException_OtherMetricsWillBeReported() throws Exception {
```
Comment (nickdella) [inline metrics-datadog/src/test/java/org/coursera/metrics/datadog/DatadogReporterTest.java]: Though the styleguide permits underscores in tests, the project isn't using them. Perhaps `reportHandlesGaugeMetricExceptions`?

File: metrics-datadog/src/main/java/org/coursera/metrics/datadog/DatadogReporter.java (hunk 3 above)
Comment (waldemar-schneider) [inline metrics-datadog/src/main/java/org/coursera/metrics/datadog/DatadogReporter.java]: What do you mean? The variable name?

File: metrics-datadog/src/main/java/org/coursera/metrics/datadog/DatadogReporter.java (hunk 1 above)
Comment (waldemar-schneider) [inline metrics-datadog/src/main/java/org/coursera/metrics/datadog/DatadogReporter.java]: Sure. Somehow I missed the part of the README at the bottom. Sorry about that :slightly_smiling_face:

File: metrics-datadog/src/test/java/org/coursera/metrics/datadog/DatadogReporterTest.java (hunk 4 above)
Comment (waldemar-schneider) [inline metrics-datadog/src/test/java/org/coursera/metrics/datadog/DatadogReporterTest.java]: Sounds good to me.

File: metrics-datadog/src/main/java/org/coursera/metrics/datadog/DatadogReporter.java (hunk 3 above)
Comment (nickdella) [inline metrics-datadog/src/main/java/org/coursera/metrics/datadog/DatadogReporter.java]: It's just a nit about the error message string. I was suggesting `Error reporting gauge metric` instead of `Error reporting gauge metrics`, as only a single metric failed in this case

**Comment by nickdella** [comment]
Thanks! I'll push a new build out tomorrow.

**Comment by waldemar-schneider** [comment]
Thanks! Much appreciated @nickdella  :slightly_smiling_face:

**Comment by nickdella** [comment]
@waldemar-schneider Just published. This should be in maven central in a few hours. FYI, I had to revert #67 to make publishing work again. Per http://central.sonatype.org/pages/apache-maven.html , `sign-artifacts` should happen at the `verify` stage, not `deploy`.  Without this in place, the sonatype release process fails because the signature files are not generated.

If you're interested in testing locally, you could just comment out the `maven-gpg-plugin` section of the pom e.g. http://www.michaelpollmeier.com/maven-skip-pgp-sign-process
